[server]
enableStaticServing = true

[theme]
# AirBnB
primaryColor = "#FF395D"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#222222"
linkColor = "#222222"
borderColor = "#DDDDDD"
showBorderAroundInputs = true
roundness = 0.333
font = "AirbnbCereal"
baseFontSize = 15

[[theme.fontFaces]]
url = "app/static/cereal/AirbnbCereal_W_Bk.otf"
family = "AirbnbCereal"
